#  File Name: installPackagesProd.yml
#  Author: Jackson Frazier
#  Use: Ansible playbook
#  Type: .yml
#  Purpose: This is a ansible playbook used for setting up a new or existing Production servers
#   with the proper packages. in this case Apache and Node.js for webServers and
#   MariaDB for databaseServers 

---
- name: Setup production web servers
  hosts: web_server_prod
  become: true

  tasks:
    - name: Install Apache and Node.js on Web Servers
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - nodejs
        - npm

- name: Setup database servers
  hosts: database_server_prod
  become: true
  tasks:
    - name: Install Apache, Node.js, and mariaDB on Database server. 
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - nodejs
        - npm
        - mariadb-server
