#  File Name: installPackagesDev.yml
#  Author: Jackson Frazier
#  Use: Ansible playbook
#  Purpose: This is a ansible playbook used for setting up a new or existing
#   Developer servers with the proper packages. in this case Apache and Node.js 
#   for webServers and MariaDB for databaseServers. Designed to be called by 
#   deploy_app.sh

---
- name: Setup Dev Web servers
  hosts: web_servers_dev
  become: true  
  tasks:
    - name: Install Apache on Web Servers
      apt:
        name: apache2
        state: present

    - name: Install Node.js on Web Servers
      apt:
        name: nodejs    
        state: present 
    

- name: Setup dev database servers
  hosts: database_servers_dev
  become: true
  tasks:
    - name: Install Apache on database Servers
      apt:
        name: apache2
        state: present
    - name: Install Node.js on database Servers
      apt:
        name: nodejs      
        state: present   

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install mariaDB on Database server.
      apt:
        name: mariadb-server
        state: present
