#  File Name: installPackagesTest.yml
#  Author: Jackson Frazier
#  Use: Ansible playbook
#  Purpose: This is a ansible playbook used for setting up a new or existing Testing
#   servers with the proper packages. in this case Apache and Node.js for webServers
#   and MariaDB for databaseServers. Designed to be called by deploy_app.sh
---
- name: Setup test Web servers
  hosts: web_servers_test
  become: true
  tasks:
        # ensures packages cache is up to date
    - name: Update apt package cache
      apt:
        update_cache: yes
         # this task was added due to a bug where the dpkg package manager would lock installation completely
    - name: Wait for APT Lock
      shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
    
    - name: Install Node.js on Web Servers
      apt:
        name: nodejs
        state: present
    - name: Install Apache on Web Servers
      apt:
        name: apache2
        state: present

- name: Setup test Database servers
  hosts: database_servers_test
  become: true
  tasks:
    
    - name: Update apt package cache
      apt:
        update_cache: yes
      # this task was added due to a bug where the dpkg package manager would lock installation completely
    - name: Wait for APT Lock
      shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
      
    - name: Install Node.js on Database Servers
      apt:
        name: nodejs
        state: present
    - name: Install Apache on Database Servers
      apt:
        name: apache2
        state: present

    - name: Install MariaDB on Database server.
      apt:
        name: mariadb-server
        state: present
