#  File Name: installPackagesProd.yml
#  Author: Jackson Frazier
#  Use: Ansible playbook
#  Purpose: This is a ansible playbook used for setting up a new or existing Production servers
#   with the proper packages. in this case Apache and Node.js for webServers and
#   MariaDB for databaseServers. Designed to be called by deploy_app.sh 
---
- name: Setup prod Web servers
  hosts: web_servers_prod
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Install Node.js on Web Servers
      apt:
        name: nodejs
        state: present
    - name: Install Apache on Web Servers
      apt:
        name: apache2
        state: present

- name: Setup prod Database servers
  hosts: database_servers_prod
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Install Node.js on Database Servers
      apt:
        name: nodejs
        state: present
    - name: Install Apache on Database Servers
      apt:
        name: apache2
        state: present

    - name: Install MariaDB on Database server.
      apt:
        name: mariadb-server
        state: present
